apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dn5ybeeqr-python
  janus-idp.io/tekton: dn5ybeeqr-python
  backstage.io/kubernetes-id: dn5ybeeqr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dn5ybeeqr-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
